# Generated by Django 4.0.2 on 2022-04-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usersdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
